"""
Report template utilities for generating Markdown and HTML reports.
"""
from typing import List, Dict, Any, Optional
from datetime import datetime
from models.change_detection import ChangeRecord


def generate_markdown_report(
    user_id: str,
    report_type: str,
    change_records: List[ChangeRecord],
    llm_insights: Dict[str, Any],
    rule_based_insights: List[str],
    generated_at: Optional[datetime] = None
) -> str:
    """
    Generate Markdown format report.
    
    Args:
        user_id: User ID
        report_type: Report type ("scheduled" or "emergency")
        change_records: List of ChangeRecord objects
        llm_insights: LLM-generated insights dict (from function call)
        rule_based_insights: Rule-based insights from Analyst Agent
        generated_at: Report generation timestamp
    
    Returns:
        Markdown formatted report string
    """
    if generated_at is None:
        generated_at = datetime.utcnow()
    
    # Header
    report_type_label = "🚨 EMERGENCY REPORT" if report_type == "emergency" else "📊 SCHEDULED REPORT"
    markdown = f"""# Competitive Intelligence Report

{report_type_label}

**Generated:** {generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}  
**User ID:** {user_id}  
**Total Changes:** {len(change_records)}  
**Critical Changes:** {sum(1 for r in change_records if r.is_critical)}

---

## Executive Summary

{llm_insights.get('summary', 'No summary available.')}

---

## Strategic Insights

"""
    
    # LLM insights
    insights = llm_insights.get('insights', [])
    if insights:
        for i, insight in enumerate(insights, 1):
            markdown += f"{i}. {insight}\n"
    else:
        markdown += "*No strategic insights generated.*\n"
    
    markdown += "\n---\n\n## Market Trends\n\n"
    
    # Market trends
    trends = llm_insights.get('market_trends', [])
    if trends:
        for trend in trends:
            markdown += f"- {trend}\n"
    else:
        markdown += "*No market trends identified.*\n"
    
    markdown += "\n---\n\n## Competitive Implications\n\n"
    
    # Competitive implications
    implications = llm_insights.get('competitive_implications', '')
    if implications:
        markdown += f"{implications}\n"
    else:
        markdown += "*No competitive implications analyzed.*\n"
    
    markdown += "\n---\n\n## Recommendations\n\n"
    
    # Recommendations
    recommendations = llm_insights.get('recommendations', [])
    if recommendations:
        for i, rec in enumerate(recommendations, 1):
            markdown += f"{i}. {rec}\n"
    else:
        markdown += "*No recommendations provided.*\n"
    
    markdown += "\n---\n\n## Detected Changes\n\n"
    
    # Change records
    if change_records:
        for i, record in enumerate(change_records, 1):
            critical_badge = "🔴 **CRITICAL**" if record.is_critical else "⚪ Normal"
            change_type_emoji = {
                "price_change": "💰",
                "limit_change": "📊",
                "tier_change": "📦",
                "feature_change": "✨"
            }.get(record.change_type, "📝")
            
            markdown += f"""### Change {i}: {change_type_emoji} {record.change_type.replace('_', ' ').title()} {critical_badge}

- **URL:** {record.url}
- **Tier:** {record.tier_name or 'N/A'}
- **Previous Value:** {record.previous_value}
- **Current Value:** {record.current_value}
"""
            
            if record.change_percent is not None:
                markdown += f"- **Change:** {record.change_percent:+.1f}%\n"
            
            markdown += f"- **Severity:** {record.severity:.2f}/1.0\n"
            markdown += f"- **Detected At:** {record.detected_at.strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
            
            if record.metadata:
                markdown += f"- **Metadata:** {record.metadata}\n"
            
            markdown += "\n"
    else:
        markdown += "*No changes detected.*\n"
    
    markdown += "\n---\n\n## Rule-Based Insights\n\n"
    
    # Rule-based insights
    if rule_based_insights:
        for insight in rule_based_insights:
            markdown += f"- {insight}\n"
    else:
        markdown += "*No rule-based insights available.*\n"
    
    markdown += f"\n---\n\n*Report generated by Agentic Market Intelligence Hub*\n"
    
    return markdown


def generate_html_report(
    user_id: str,
    report_type: str,
    change_records: List[ChangeRecord],
    llm_insights: Dict[str, Any],
    rule_based_insights: List[str],
    generated_at: Optional[datetime] = None
) -> str:
    """
    Generate HTML format report (simple, email-friendly).
    
    Args:
        user_id: User ID
        report_type: Report type ("scheduled" or "emergency")
        change_records: List of ChangeRecord objects
        llm_insights: LLM-generated insights dict
        rule_based_insights: Rule-based insights from Analyst Agent
        generated_at: Report generation timestamp
    
    Returns:
        HTML formatted report string
    """
    if generated_at is None:
        generated_at = datetime.utcnow()
    
    report_type_label = "🚨 EMERGENCY REPORT" if report_type == "emergency" else "📊 SCHEDULED REPORT"
    critical_count = sum(1 for r in change_records if r.is_critical)
    
    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #34495e; margin-top: 30px; }}
        h3 {{ color: #555; }}
        .header {{ background: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 20px; }}
        .critical {{ color: #e74c3c; font-weight: bold; }}
        .change-item {{ background: #f8f9fa; padding: 15px; margin: 10px 0; border-left: 4px solid #3498db; border-radius: 3px; }}
        .insight {{ padding: 10px; margin: 5px 0; background: #e8f5e9; border-radius: 3px; }}
        .recommendation {{ padding: 10px; margin: 5px 0; background: #fff3e0; border-radius: 3px; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #777; font-size: 0.9em; }}
    </style>
</head>
<body>
    <h1>Competitive Intelligence Report</h1>
    
    <div class="header">
        <p><strong>{report_type_label}</strong></p>
        <p><strong>Generated:</strong> {generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
        <p><strong>User ID:</strong> {user_id}</p>
        <p><strong>Total Changes:</strong> {len(change_records)}</p>
        <p><strong>Critical Changes:</strong> <span class="critical">{critical_count}</span></p>
    </div>
    
    <h2>Executive Summary</h2>
    <p>{llm_insights.get('summary', 'No summary available.')}</p>
    
    <h2>Strategic Insights</h2>
"""
    
    # LLM insights
    insights = llm_insights.get('insights', [])
    if insights:
        for i, insight in enumerate(insights, 1):
            html += f'    <div class="insight"><strong>{i}.</strong> {insight}</div>\n'
    else:
        html += '    <p><em>No strategic insights generated.</em></p>\n'
    
    html += '    <h2>Market Trends</h2>\n    <ul>\n'
    
    # Market trends
    trends = llm_insights.get('market_trends', [])
    if trends:
        for trend in trends:
            html += f'        <li>{trend}</li>\n'
    else:
        html += '        <li><em>No market trends identified.</em></li>\n'
    
    html += '    </ul>\n    <h2>Competitive Implications</h2>\n    <p>'
    
    # Competitive implications
    implications = llm_insights.get('competitive_implications', '')
    if implications:
        html += f'{implications}'
    else:
        html += '<em>No competitive implications analyzed.</em>'
    
    html += '</p>\n    <h2>Recommendations</h2>\n    <ol>\n'
    
    # Recommendations
    recommendations = llm_insights.get('recommendations', [])
    if recommendations:
        for rec in recommendations:
            html += f'        <li class="recommendation">{rec}</li>\n'
    else:
        html += '        <li><em>No recommendations provided.</em></li>\n'
    
    html += '    </ol>\n    <h2>Detected Changes</h2>\n'
    
    # Change records
    if change_records:
        for i, record in enumerate(change_records, 1):
            critical_class = 'critical' if record.is_critical else ''
            change_type_emoji = {
                "price_change": "💰",
                "limit_change": "📊",
                "tier_change": "📦",
                "feature_change": "✨"
            }.get(record.change_type, "📝")
            
            html += f"""    <div class="change-item">
        <h3>{change_type_emoji} Change {i}: {record.change_type.replace('_', ' ').title()} <span class="{critical_class}">{'[CRITICAL]' if record.is_critical else ''}</span></h3>
        <ul>
            <li><strong>URL:</strong> {record.url}</li>
            <li><strong>Tier:</strong> {record.tier_name or 'N/A'}</li>
            <li><strong>Previous Value:</strong> {record.previous_value}</li>
            <li><strong>Current Value:</strong> {record.current_value}</li>
"""
            
            if record.change_percent is not None:
                html += f'            <li><strong>Change:</strong> {record.change_percent:+.1f}%</li>\n'
            
            html += f"""            <li><strong>Severity:</strong> {record.severity:.2f}/1.0</li>
            <li><strong>Detected At:</strong> {record.detected_at.strftime('%Y-%m-%d %H:%M:%S UTC')}</li>
"""
            
            if record.metadata:
                html += f'            <li><strong>Metadata:</strong> {record.metadata}</li>\n'
            
            html += '        </ul>\n    </div>\n'
    else:
        html += '    <p><em>No changes detected.</em></p>\n'
    
    html += '    <h2>Rule-Based Insights</h2>\n    <ul>\n'
    
    # Rule-based insights
    if rule_based_insights:
        for insight in rule_based_insights:
            html += f'        <li>{insight}</li>\n'
    else:
        html += '        <li><em>No rule-based insights available.</em></li>\n'
    
    html += """    </ul>
    
    <div class="footer">
        <p><em>Report generated by Agentic Market Intelligence Hub</em></p>
    </div>
</body>
</html>"""
    
    return html

