"""
Report data models.
"""
from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any
from datetime import datetime


class Report(BaseModel):
    """
    Report model for competitive intelligence reports.
    """
    report_id: str = Field(..., description="Unique report identifier (UUID)")
    user_id: str = Field(..., description="User who owns this report")
    report_type: str = Field(
        ...,
        description="Report type: 'scheduled' or 'emergency'"
    )
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    changes_detected: int = Field(
        default=0,
        description="Total number of changes detected"
    )
    critical_changes: int = Field(
        default=0,
        description="Number of critical changes (exceeding threshold)"
    )
    changes: List[Dict] = Field(
        default_factory=list,
        description="List of detected changes"
    )
    insights: List[str] = Field(
        default_factory=list,
        description="Strategic insights generated by LLM"
    )
    report_content: str = Field(
        default="",
        description="Full report content in Markdown/HTML format"
    )
    email_sent: bool = Field(
        default=False,
        description="Whether email notification was sent"
    )
    email_sent_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when email was sent"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata (e.g., LLM-generated subtitle or subject)"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "report_id": "report_123",
                "user_id": "user_456",
                "report_type": "scheduled",
                "generated_at": "2024-01-01T12:00:00Z",
                "changes_detected": 3,
                "critical_changes": 1,
                "changes": [
                    {
                        "url": "https://vercel.com/pricing",
                        "type": "price_change",
                        "tier": "pro",
                        "previous": 20,
                        "current": 25,
                        "change_percent": 25.0,
                        "severity": 0.9
                    }
                ],
                "insights": [
                    "Vercel increased Pro tier pricing by 25%",
                    "This may indicate market positioning shift"
                ],
                "email_sent": True
            }
        }
